// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orders.DataAccess.Context;

#nullable disable

namespace Orders.DataAccess.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    [Migration("20240222141432_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Orders.DattaAcces.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "New York Building 1",
                            State = "NY"
                        },
                        new
                        {
                            Id = 2,
                            Name = "California Hotel AJK",
                            State = "CA"
                        });
                });

            modelBuilder.Entity("Orders.DattaAcces.Entities.SubElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Element")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WindowId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WindowId");

                    b.ToTable("SubElements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Element = 1,
                            Height = 1850,
                            Type = "Doors",
                            Width = 1200,
                            WindowId = 1
                        },
                        new
                        {
                            Id = 2,
                            Element = 2,
                            Height = 1850,
                            Type = "Window",
                            Width = 800,
                            WindowId = 1
                        },
                        new
                        {
                            Id = 3,
                            Element = 3,
                            Height = 1850,
                            Type = "Window",
                            Width = 700,
                            WindowId = 1
                        },
                        new
                        {
                            Id = 4,
                            Element = 1,
                            Height = 2000,
                            Type = "Window",
                            Width = 1500,
                            WindowId = 2
                        },
                        new
                        {
                            Id = 5,
                            Element = 1,
                            Height = 2200,
                            Type = "Doors",
                            Width = 1400,
                            WindowId = 3
                        },
                        new
                        {
                            Id = 6,
                            Element = 2,
                            Height = 2200,
                            Type = "Window",
                            Width = 600,
                            WindowId = 3
                        },
                        new
                        {
                            Id = 7,
                            Element = 1,
                            Height = 2000,
                            Type = "Window",
                            Width = 1500,
                            WindowId = 4
                        },
                        new
                        {
                            Id = 8,
                            Element = 1,
                            Height = 2000,
                            Type = "Window",
                            Width = 1500,
                            WindowId = 4
                        });
                });

            modelBuilder.Entity("Orders.DattaAcces.Entities.Window", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityOfWindows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSubElements")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Windows");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A51",
                            OrderId = 1,
                            QuantityOfWindows = 4,
                            TotalSubElements = 3
                        },
                        new
                        {
                            Id = 2,
                            Name = "C Zone 5",
                            OrderId = 1,
                            QuantityOfWindows = 2,
                            TotalSubElements = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "GLB",
                            OrderId = 2,
                            QuantityOfWindows = 3,
                            TotalSubElements = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "OHF",
                            OrderId = 2,
                            QuantityOfWindows = 10,
                            TotalSubElements = 2
                        });
                });

            modelBuilder.Entity("Orders.DattaAcces.Entities.SubElement", b =>
                {
                    b.HasOne("Orders.DattaAcces.Entities.Window", "Window")
                        .WithMany("SubElements")
                        .HasForeignKey("WindowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Window");
                });

            modelBuilder.Entity("Orders.DattaAcces.Entities.Window", b =>
                {
                    b.HasOne("Orders.DattaAcces.Entities.Order", "Order")
                        .WithMany("Windows")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Orders.DattaAcces.Entities.Order", b =>
                {
                    b.Navigation("Windows");
                });

            modelBuilder.Entity("Orders.DattaAcces.Entities.Window", b =>
                {
                    b.Navigation("SubElements");
                });
#pragma warning restore 612, 618
        }
    }
}
